services:
  cron:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "while true; do python purge_expired_reservations.py; sleep 14400; done"
    depends_on:
      - mysql
    networks:
      - appnet
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: bibolib-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bibolib
      MYSQL_USER: bibolib_user
      MYSQL_PASSWORD: bibolib_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/bibolib_db.sql:/docker-entrypoint-initdb.d/bibolib.sql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  activity_logs:
    build:
      context: ./activity_logs
    ports:
      - "8080:8080"
    networks:
      - appnet
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      activity_logs:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - appnet
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql+pymysql://bibolib_user:bibolib_password@mysql:3306/bibolib
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - appnet
    env_file:
      - .env


volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
