// Données de démonstration pour l'application

export const demoLibraries = [
  {
    id: 1,
    name: "Bibliothèque Forney",
    address: "1 Rue du Figuier, 75004 Paris",
    arrondissement: "4e",
    phone: "01 42 78 14 60",
    email: "contact@forney.paris.fr",
    hours: "Mar-Sam: 10h-19h, Dim: 13h-19h",
    description: "Spécialisée dans les arts décoratifs, les beaux-arts et les métiers d'art. La bibliothèque Forney conserve plus de 200 000 ouvrages.",
    isOpen: true,
    bookCount: 1250,
    website: "https://www.paris.fr/equipements/bibliotheque-forney-1735"
  },
  {
    id: 2,
    name: "Bibliothèque Marguerite Audoux",
    address: "10 Rue Portefoin, 75003 Paris",
    arrondissement: "3e",
    phone: "01 44 78 80 50",
    email: "contact@audoux.paris.fr",
    hours: "Mar-Ven: 14h-19h, Sam: 10h-18h",
    description: "Bibliothèque de quartier proposant une collection généraliste avec un fonds jeunesse important et des espaces de travail confortables.",
    isOpen: true,
    bookCount: 890,
    website: "https://www.paris.fr/equipements/bibliotheque-marguerite-audoux-1738"
  },
  {
    id: 3,
    name: "Bibliothèque Crimée",
    address: "208 Rue de Crimée, 75019 Paris",
    arrondissement: "19e",
    phone: "01 40 34 90 00",
    email: "contact@crimee.paris.fr",
    hours: "Mar-Ven: 15h-19h, Sam: 10h-18h",
    description: "Une des plus grandes bibliothèques du réseau parisien, offrant de nombreux espaces de lecture et une programmation culturelle riche.",
    isOpen: false,
    bookCount: 1500,
    website: "https://www.paris.fr/equipements/bibliotheque-crimee-1742"
  },
  {
    id: 4,
    name: "Bibliothèque André Malraux",
    address: "78 Boulevard Raspail, 75006 Paris",
    arrondissement: "6e",
    phone: "01 45 44 53 85",
    email: "contact@malraux.paris.fr",
    hours: "Lun-Ven: 10h-19h, Sam: 10h-17h",
    description: "Bibliothèque moderne au cœur de Saint-Germain, proposant une large collection littéraire et des espaces numériques équipés.",
    isOpen: true,
    bookCount: 2100,
    website: "https://www.paris.fr/equipements/bibliotheque-andre-malraux-1745"
  },
  {
    id: 5,
    name: "Bibliothèque Françoise Sagan",
    address: "8 Rue Léon Schwartzenberg, 75010 Paris",
    arrondissement: "10e",
    phone: "01 53 24 69 70",
    email: "contact@sagan.paris.fr",
    hours: "Mar-Ven: 13h-19h, Sam: 10h-18h",
    description: "Bibliothèque contemporaine offrant des collections variées et des espaces dédiés au multimédia et au travail collaboratif.",
    isOpen: true,
    bookCount: 1680,
    website: "https://www.paris.fr/equipements/bibliotheque-francoise-sagan-1748"
  },
  {
    id: 6,
    name: "Bibliothèque Chaptal",
    address: "26 Rue Chaptal, 75009 Paris",
    arrondissement: "9e",
    phone: "01 44 78 80 50",
    email: "contact@chaptal.paris.fr",
    hours: "Mar-Sam: 10h-19h",
    description: "Située dans une ancienne école, cette bibliothèque allie patrimoine architectural et modernité avec ses collections spécialisées.",
    isOpen: true,
    bookCount: 950,
    website: "https://www.paris.fr/equipements/bibliotheque-chaptal-1751"
  }
];

export const demoBooks = [
  {
    id: 1,
    title: "Le Livre de la Jungle",
    author: "Rudyard Kipling",
    year: 1894,
    isbn: "978-2-07-040832-4",
    genre: "Aventure",
    pages: 256,
    language: "Français",
    publisher: "Gallimard",
    status: "available", // available, reserved, borrowed
    libraryId: 1,
    libraryName: "Bibliothèque Forney",
    description: "Les aventures de Mowgli, un petit garçon élevé par les loups dans la jungle indienne.",
    summary: "Un classique de la littérature jeunesse qui nous emmène dans la jungle indienne à la découverte des aventures extraordinaires de Mowgli. Ce livre emblématique explore les thèmes de l'identité, de l'appartenance et de la nature sauvage.",
    tags: ["Classique", "Aventure", "Jeunesse", "Nature", "Animaux"],
    rating: 4.5,
    borrowCount: 1247,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    year: 1949,
    isbn: "978-2-07-036822-5",
    genre: "Science-Fiction",
    pages: 384,
    language: "Français",
    publisher: "Gallimard",
    status: "reserved",
    libraryId: 2,
    libraryName: "Bibliothèque Marguerite Audoux",
    description: "Un roman dystopique sur la surveillance et le totalitarisme dans une société futuriste.",
    summary: "Dans un monde où la vérité est constamment réécrite par le Parti, Winston Smith travaille au Ministère de la Vérité. Ce chef-d'œuvre de la littérature explore les thèmes de la liberté, de la vérité et de la résistance face à l'oppression.",
    tags: ["Dystopie", "Politique", "Classique", "Anticipation"],
    rating: 4.7,
    borrowCount: 2156,
    coverImage: null,
    downloadLink: null,
    reservedBy: 3, // Jean Martin
    reservedAt: "2024-10-05T14:30:00.000Z",
    reservationExpires: "2024-10-08T14:30:00.000Z",
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 3,
    title: "Le Petit Prince",
    author: "Antoine de Saint-Exupéry",
    year: 1943,
    isbn: "978-2-07-040850-8",
    genre: "Fiction",
    pages: 96,
    language: "Français",
    publisher: "Gallimard",
    status: "borrowed",
    libraryId: 4,
    libraryName: "Bibliothèque André Malraux",
    description: "L'histoire touchante d'un petit prince qui voyage de planète en planète.",
    summary: "Un conte philosophique qui nous invite à redécouvrir l'essentiel à travers les yeux d'un enfant. Une œuvre universelle sur l'amitié, l'amour et le sens de la vie.",
    tags: ["Conte", "Philosophie", "Jeunesse", "Classique"],
    rating: 4.8,
    borrowCount: 3421,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: 4, // Sophie Leroy
    borrowedAt: "2024-10-03T09:15:00.000Z",
    dueDate: "2024-10-17T23:59:00.000Z"
  },
  {
    id: 4,
    title: "L'Étranger",
    author: "Albert Camus",
    year: 1942,
    isbn: "978-2-07-036002-1",
    genre: "Fiction",
    pages: 128,
    language: "Français",
    publisher: "Gallimard",
    status: "available",
    libraryId: 1,
    libraryName: "Bibliothèque Forney",
    description: "L'histoire de Meursault, un homme indifférent face à l'existence.",
    summary: "Premier roman de Camus, L'Étranger nous confronte à l'absurdité de la condition humaine à travers le personnage de Meursault, indifférent aux conventions sociales.",
    tags: ["Existentialisme", "Philosophie", "Classique", "Prix Nobel"],
    rating: 4.3,
    borrowCount: 1876,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 5,
    title: "Les Misérables",
    author: "Victor Hugo",
    year: 1862,
    isbn: "978-2-07-041945-0",
    genre: "Classique",
    pages: 1232,
    language: "Français",
    publisher: "Gallimard",
    status: "available",
    libraryId: 3,
    libraryName: "Bibliothèque Crimée",
    description: "L'épopée de Jean Valjean dans la France du XIXe siècle.",
    summary: "Une fresque sociale monumentale qui dépeint la France du XIXe siècle à travers le destin de Jean Valjean. Hugo y dénonce les injustices sociales et exalte la rédemption par l'amour.",
    tags: ["Classique", "Histoire", "Social", "Romantisme"],
    rating: 4.6,
    borrowCount: 987,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 6,
    title: "Le Comte de Monte-Cristo",
    author: "Alexandre Dumas",
    year: 1844,
    isbn: "978-2-07-041234-5",
    genre: "Aventure",
    pages: 1024,
    language: "Français",
    publisher: "Gallimard",
    status: "borrowed",
    libraryId: 5,
    libraryName: "Bibliothèque Françoise Sagan",
    description: "L'histoire d'Edmond Dantès et de sa quête de vengeance.",
    summary: "Un des plus grands romans d'aventures de la littérature française. L'histoire passionnante d'Edmond Dantès, injustement emprisonné, qui s'évade pour se venger de ses ennemis.",
    tags: ["Aventure", "Vengeance", "Classique", "Cape et épée"],
    rating: 4.5,
    borrowCount: 1543,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: 7, // Paul Durand
    borrowedAt: "2024-10-04T16:20:00.000Z",
    dueDate: "2024-10-18T23:59:00.000Z"
  },
  {
    id: 7,
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    year: 1857,
    isbn: "978-2-07-041456-1",
    genre: "Classique",
    pages: 384,
    language: "Français",
    publisher: "Gallimard",
    status: "available",
    libraryId: 6,
    libraryName: "Bibliothèque Chaptal",
    description: "L'histoire d'Emma Bovary, une femme en quête d'absolu.",
    summary: "Chef-d'œuvre du réalisme français, ce roman raconte l'histoire tragique d'Emma Bovary, une femme romantique en quête d'un idéal impossible dans la société bourgeoise du XIXe siècle.",
    tags: ["Réalisme", "Classique", "Psychologie", "Société"],
    rating: 4.2,
    borrowCount: 756,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 8,
    title: "Le Rouge et le Noir",
    author: "Stendhal",
    year: 1830,
    isbn: "978-2-07-041789-0",
    genre: "Classique",
    pages: 512,
    language: "Français",
    publisher: "Gallimard",
    status: "available",
    libraryId: 2,
    libraryName: "Bibliothèque Marguerite Audoux",
    description: "Les ambitions de Julien Sorel dans la France de la Restauration.",
    summary: "Roman d'apprentissage et d'analyse sociale, l'œuvre suit Julien Sorel, jeune homme ambitieux naviguant entre l'Église et l'armée pour s'élever dans la société.",
    tags: ["Romantisme", "Société", "Ambition", "Classique"],
    rating: 4.1,
    borrowCount: 892,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null
  },
  {
    id: 9,
    title: "Dune",
    author: "Frank Herbert",
    year: 1965,
    isbn: "978-2-266-32029-8",
    genre: "Science-Fiction",
    pages: 688,
    language: "Français",
    publisher: "Pocket",
    status: "available",
    libraryId: 1,
    libraryName: "Bibliothèque Forney",
    description: "Sur la planète Arrakis, Paul Atréides mène une révolution qui changera l'univers.",
    summary: "Chef-d'œuvre de la science-fiction, Dune nous emmène sur la planète désertique d'Arrakis où se mêlent politique galactique, écologie et mysticisme.",
    tags: ["Science-Fiction", "Épique", "Écologie", "Politique"],
    rating: 4.7,
    borrowCount: 2134,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null,
    isNew: true,
    addedAt: "2024-10-01T00:00:00.000Z"
  },
  {
    id: 10,
    title: "Klara et le Soleil",
    author: "Kazuo Ishiguro",
    year: 2021,
    isbn: "978-2-07-293847-2",
    genre: "Science-Fiction",
    pages: 384,
    language: "Français",
    publisher: "Gallimard",
    status: "available",
    libraryId: 2,
    libraryName: "Bibliothèque Marguerite Audoux",
    description: "L'histoire touchante de Klara, une Amie Artificielle qui observe le monde avec une curiosité infinie.",
    summary: "Prix Nobel de littérature, Kazuo Ishiguro nous livre un roman bouleversant sur l'amour, l'espoir et ce qui fait notre humanité.",
    tags: ["Science-Fiction", "Prix Nobel", "Intelligence Artificielle", "Émotion"],
    rating: 4.4,
    borrowCount: 567,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null,
    isNew: true,
    addedAt: "2024-09-28T00:00:00.000Z"
  },
  {
    id: 11,
    title: "L'Anomalie",
    author: "Hervé Le Tellier",
    year: 2020,
    isbn: "978-2-07-287042-8",
    genre: "Science-Fiction",
    pages: 336,
    language: "Français",
    publisher: "Gallimard",
    status: "reserved",
    libraryId: 3,
    libraryName: "Bibliothèque Crimée",
    description: "Un vol Paris-New York atterrit deux fois... Prix Goncourt 2020.",
    summary: "Prix Goncourt 2020, ce roman bouleversant interroge notre identité et nos choix dans un récit à la fois drôle et philosophique.",
    tags: ["Prix Goncourt", "Science-Fiction", "Philosophie", "Contemporain"],
    rating: 4.3,
    borrowCount: 1893,
    coverImage: null,
    downloadLink: null,
    reservedBy: 8, // Emma Bernard
    reservedAt: "2024-10-04T10:15:00.000Z",
    reservationExpires: "2024-10-07T10:15:00.000Z",
    borrowedBy: null,
    borrowedAt: null,
    dueDate: null,
    isNew: true,
    addedAt: "2024-09-25T00:00:00.000Z"
  },
  {
    id: 12,
    title: "La Daronne",
    author: "Hannelore Cayre",
    year: 2017,
    isbn: "978-2-07-279654-2",
    genre: "Polar",
    pages: 240,
    language: "Français",
    publisher: "Métailié",
    status: "borrowed",
    libraryId: 4,
    libraryName: "Bibliothèque André Malraux",
    description: "Une traductrice de police judiciaire devient la plus grande dealease de Paris.",
    summary: "Prix du Polar européen, ce roman déjanté et hilarant nous plonge dans les bas-fonds parisiens avec un humour féroce.",
    tags: ["Polar", "Humour", "Paris", "Prix"],
    rating: 4.2,
    borrowCount: 1245,
    coverImage: null,
    downloadLink: null,
    reservedBy: null,
    reservedAt: null,
    reservationExpires: null,
    borrowedBy: 6, // Alice Moreau
    borrowedAt: "2024-10-02T14:20:00.000Z",
    dueDate: "2024-10-16T23:59:00.000Z",
    isNew: false,
    addedAt: "2024-08-15T00:00:00.000Z"
  }
];

export const demoUsers = [
  // Admins
  {
    id: 1,
    name: "Admin Principal",
  email: "admin@bibliotheque.local",
    password: "admin123",
    role: "admin",
    createdAt: "2024-01-01T00:00:00.000Z",
    lastLogin: "2024-10-06T10:30:00.000Z"
  },
  {
    id: 2,
    name: "Marie Dubois",
  email: "marie.dubois@bibliotheque.local",
    password: "marie123",
    role: "moderator",
    createdAt: "2024-02-15T00:00:00.000Z",
    lastLogin: "2024-10-05T14:20:00.000Z"
  },
  // Utilisateurs normaux
  {
    id: 3,
    name: "Jean Martin",
    email: "jean.martin@gmail.com",
    password: "jean123",
    role: "user",
    createdAt: "2024-03-10T00:00:00.000Z",
    lastLogin: "2024-10-04T16:45:00.000Z"
  },
  {
    id: 4,
    name: "Sophie Leroy",
    email: "sophie.leroy@yahoo.fr",
    password: "sophie123",
    role: "user",
    createdAt: "2024-04-22T00:00:00.000Z",
    lastLogin: "2024-10-03T09:15:00.000Z"
  },
  {
    id: 5,
    name: "Pierre Suspect",
    email: "pierre.suspect@fake.com",
    password: "pierre123",
    role: "user",
    createdAt: "2024-10-05T00:00:00.000Z",
    lastLogin: "2024-10-05T23:59:00.000Z"
  },
  {
    id: 6,
    name: "Alice Moreau",
    email: "alice.moreau@outlook.com",
    password: "alice123",
    role: "moderator",
    createdAt: "2024-05-18T00:00:00.000Z",
    lastLogin: "2024-10-06T08:30:00.000Z"
  },
  {
    id: 7,
    name: "Paul Durand",
    email: "paul.durand@hotmail.fr",
    password: "paul123",
    role: "user",
    createdAt: "2024-06-10T00:00:00.000Z",
    lastLogin: "2024-10-05T11:20:00.000Z"
  },
  {
    id: 8,
    name: "Emma Bernard",
    email: "emma.bernard@gmail.com",
    password: "emma123",
    role: "user",
    createdAt: "2024-07-08T00:00:00.000Z",
    lastLogin: "2024-10-06T07:45:00.000Z"
  }
];

// Garder l'ancien export pour compatibilité
export const demoAdmins = demoUsers;

// Genres disponibles
export const availableGenres = [
  'Aventure', 'Biographie', 'Classique', 'Comédie', 'Drame', 'Essai',
  'Fantastique', 'Fiction', 'Histoire', 'Horreur', 'Jeunesse', 'Mystère',
  'Philosophie', 'Poésie', 'Politique', 'Romance', 'Science-Fiction', 'Thriller'
];

// Arrondissements
export const availableArrondissements = [
  '1er', '2e', '3e', '4e', '5e', '6e', '7e', '8e', '9e', '10e',
  '11e', '12e', '13e', '14e', '15e', '16e', '17e', '18e', '19e', '20e'
];